'use client'

import { useState } from 'react'

interface AITransparencyProps {
  visitSummary?: string
  fullTranscript?: string
  recordingUrl?: string
  className?: string
}

const AITransparency = ({ 
  visitSummary = "Patient presented for routine follow-up. Discussed medication compliance and lifestyle modifications.",
  fullTranscript = "Doctor: How are you feeling today?\nPatient: I'm doing well, taking my medications as prescribed.\nDoctor: Any side effects?\nPatient: No, everything seems fine.",
  recordingUrl,
  className = ""
}: AITransparencyProps) => {
  const [showModal, setShowModal] = useState(false)
  const [activeTab, setActiveTab] = useState('summary')

  return (
    <>
      <button
        onClick={() => setShowModal(true)}
        className={`flex items-center gap-1 text-xs text-gray-500 dark:text-gray-400 hover:text-primary transition-colors ${className}`}
        title="View AI transparency details"
      >
        <span className="material-symbols-outlined text-sm">psychology</span>
        AI Details
      </button>

      {showModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-gray-900 rounded-xl w-full max-w-4xl max-h-[90vh] overflow-hidden">
            <div className="flex items-center justify-between p-6 border-b border-gray-200 dark:border-gray-700">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white">AI Transparency & Safety Review</h3>
              <button
                onClick={() => setShowModal(false)}
                className="p-2 text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg"
              >
                <span className="material-symbols-outlined">close</span>
              </button>
            </div>

            <div className="flex border-b border-gray-200 dark:border-gray-700">
              {[
                { id: 'summary', label: 'Visit Summary', icon: 'summarize' },
                { id: 'transcript', label: 'Full Transcript', icon: 'transcript' },
                ...(recordingUrl ? [{ id: 'recording', label: 'Recording', icon: 'play_circle' }] : [])
              ].map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`flex items-center gap-2 px-4 py-3 text-sm font-medium border-b-2 transition-colors ${
                    activeTab === tab.id
                      ? 'border-primary text-primary'
                      : 'border-transparent text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white'
                  }`}
                >
                  <span className="material-symbols-outlined text-sm">{tab.icon}</span>
                  {tab.label}
                </button>
              ))}
            </div>

            <div className="p-6 overflow-y-auto max-h-[60vh]">
              {activeTab === 'summary' && (
                <div className="space-y-4">
                  <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-lg">
                    <div className="flex items-center gap-2 mb-2">
                      <span className="material-symbols-outlined text-blue-600 dark:text-blue-400">info</span>
                      <span className="text-sm font-medium text-blue-800 dark:text-blue-200">AI-Generated Summary</span>
                    </div>
                    <p className="text-sm text-blue-700 dark:text-blue-300">
                      This summary was automatically generated by AI. Please review for accuracy.
                    </p>
                  </div>
                  <div className="prose dark:prose-invert max-w-none">
                    <p className="text-gray-700 dark:text-gray-300">{visitSummary}</p>
                  </div>
                </div>
              )}

              {activeTab === 'transcript' && (
                <div className="space-y-4">
                  <div className="bg-yellow-50 dark:bg-yellow-900/20 p-4 rounded-lg">
                    <div className="flex items-center gap-2 mb-2">
                      <span className="material-symbols-outlined text-yellow-600 dark:text-yellow-400">warning</span>
                      <span className="text-sm font-medium text-yellow-800 dark:text-yellow-200">Speech-to-Text Transcript</span>
                    </div>
                    <p className="text-sm text-yellow-700 dark:text-yellow-300">
                      This transcript was generated using speech recognition. Some inaccuracies may exist.
                    </p>
                  </div>
                  <div className="bg-gray-50 dark:bg-gray-800 p-4 rounded-lg">
                    <pre className="whitespace-pre-wrap text-sm text-gray-700 dark:text-gray-300 font-mono">
                      {fullTranscript}
                    </pre>
                  </div>
                </div>
              )}

              {activeTab === 'recording' && recordingUrl && (
                <div className="space-y-4">
                  <div className="bg-green-50 dark:bg-green-900/20 p-4 rounded-lg">
                    <div className="flex items-center gap-2 mb-2">
                      <span className="material-symbols-outlined text-green-600 dark:text-green-400">mic</span>
                      <span className="text-sm font-medium text-green-800 dark:text-green-200">Original Recording</span>
                    </div>
                    <p className="text-sm text-green-700 dark:text-green-300">
                      Original audio recording for verification purposes.
                    </p>
                  </div>
                  <div className="bg-white dark:bg-gray-800 p-4 rounded-lg border border-gray-200 dark:border-gray-700">
                    <audio controls className="w-full">
                      <source src={recordingUrl} type="audio/mpeg" />
                      Your browser does not support the audio element.
                    </audio>
                  </div>
                </div>
              )}
            </div>

            <div className="p-6 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800">
              <div className="flex items-center justify-between">
                <div className="text-xs text-gray-500 dark:text-gray-400">
                  AI processing completed at {new Date().toLocaleString()}
                </div>
                <button
                  onClick={() => setShowModal(false)}
                  className="px-4 py-2 bg-primary text-white rounded-lg hover:bg-primary/90 text-sm font-medium"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  )
}

export default AITransparency